project:
  type: website

website:
  title: "quartoon"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/anicricket
      - icon: twitter
        href: https://twitter.com/FabrizioRomano
format:
  html:
    theme: cosmo
    css: styles.css



